### ISSUE TITLE
For Windows split Path char is ';'

### ISSUE THREAD

**Issue by wisemoth** [necatiarslan/environment-variables-vscode-extension#1]
A handy plugin, which almost works on Windows - but the Path list separator is '`;'` on Windows so you see this kind of thing:

![image](https://github.com/necatiarslan/environment-variables-vscode-extension/assets/26512373/fde7581a-5f26-438f-9118-eed83578f21b)

Perhaps this line on platform OS:
https://github.com/necatiarslan/environment-variables-vscode-extension/blob/main/src/treeDataProvider.ts#L44

**Comment by necatiarslan** [comment]
fixed with new version 1.0.3
pls update and let me know if it works

**Comment by wisemoth** [comment]
Works perfectly, many thanks!
